name: CI/CD Docker Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin


      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/waba-backend:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/waba-backend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/waba-backend-v2
            docker compose pull
            docker compose up -d --remove-orphans

      # 5Ô∏è‚É£ Notify Telegram
      - name: Notify Telegram
        if: always()
        run: |
          STATUS="${{ job.status }}"
          REPO="${{ github.repository }}"
          BRANCH="${{ github.ref_name }}"
          USER="${{ github.actor }}"
          COMMIT_HASH="${{ github.sha }}"
          SHORT_HASH=$(echo "${COMMIT_HASH}" | cut -c1-7)
          DATETIME=$(date -u +"%d %B %y, %-I:%M %p" --date "+8 hours")" (UTC +8)"

          if [ "$STATUS" == "success" ]; then
            STATUS_TEXT="Success ‚úÖ"
          else
            STATUS_TEXT="Failed ‚ùå"
          fi

          MSG=$(cat <<EOF
          üöÄ Deployment to *${REPO}*

          With *Docker* üê≥
          Revision: $SHORT_HASH
          Status: $STATUS_TEXT
          Branch: $BRANCH
          DateTime: $DATETIME
          Author: $USER
          EOF
          )

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d parse_mode="HTML" \
            --data-urlencode "text=$MSG"

